package catalog

var Entries = []AppDef{
	{Name: "Google Chrome", ID: "Google.Chrome", Category: "BÖNGÉSZŐK"},
	{Name: "Mozilla Firefox", ID: "Mozilla.Firefox", Category: "BÖNGÉSZŐK"},
	{Name: "Microsoft Edge", ID: "Microsoft.Edge", Category: "BÖNGÉSZŐK"},
	{Name: "Brave", ID: "Brave.Brave", Category: "BÖNGÉSZŐK"},
	{Name: "Opera", ID: "Opera.Opera", Category: "BÖNGÉSZŐK"},
	{Name: "Vivaldi", ID: "Vivaldi.Vivaldi", Category: "BÖNGÉSZŐK"},
	{Name: "Zoom", ID: "Zoom.Zoom", Category: "KOMMUNIKÁCIÓ"},
	{Name: "Discord", ID: "Discord.Discord", Category: "KOMMUNIKÁCIÓ"},
	{Name: "Microsoft Teams", ID: "Microsoft.Teams", Category: "KOMMUNIKÁCIÓ"},
	{Name: "Pidgin", ID: "", Category: "KOMMUNIKÁCIÓ"},
	{Name: "Mozilla Thunderbird", ID: "Mozilla.Thunderbird", Category: "KOMMUNIKÁCIÓ"},
	{Name: "Trillian", ID: "", Category: "KOMMUNIKÁCIÓ"},
	{Name: "Telegram Desktop", ID: "Telegram.TelegramDesktop", Category: "KOMMUNIKÁCIÓ"},
	{Name: "iTunes", ID: "", Category: "MÉDIA / ZENE / VIDEÓ"},
	{Name: "VLC Media Player", ID: "VideoLAN.VLC", Category: "MÉDIA / ZENE / VIDEÓ"},
	{Name: "AIMP", ID: "", Category: "MÉDIA / ZENE / VIDEÓ"},
	{Name: "foobar2000", ID: "", Category: "MÉDIA / ZENE / VIDEÓ"},
	{Name: "Winamp", ID: "", Category: "MÉDIA / ZENE / VIDEÓ"},
	{Name: "MusicBee", ID: "", Category: "MÉDIA / ZENE / VIDEÓ"},
	{Name: "Audacity", ID: "Audacity.Audacity", Category: "MÉDIA / ZENE / VIDEÓ"},
	{Name: "K-Lite Codec Pack", ID: "", Category: "MÉDIA / ZENE / VIDEÓ"},
	{Name: "GOM Player", ID: "", Category: "MÉDIA / ZENE / VIDEÓ"},
	{Name: "Spotify", ID: "Spotify.Spotify", Category: "MÉDIA / ZENE / VIDEÓ"},
	{Name: "Combined Community Codec Pack (CCCP)", ID: "", Category: "MÉDIA / ZENE / VIDEÓ"},
	{Name: "MediaMonkey", ID: "", Category: "MÉDIA / ZENE / VIDEÓ"},
	{Name: "HandBrake", ID: "HandBrake.HandBrake", Category: "MÉDIA / ZENE / VIDEÓ"},
	{Name: "Krita", ID: "KDE.Krita", Category: "GRAFIKA / KÉP / VIDEÓ"},
	{Name: "Blender", ID: "BlenderFoundation.Blender", Category: "GRAFIKA / KÉP / VIDEÓ"},
	{Name: "Paint.NET", ID: "dotPDN.PaintDotNet", Category: "GRAFIKA / KÉP / VIDEÓ"},
	{Name: "GIMP", ID: "GIMP.GIMP", Category: "GRAFIKA / KÉP / VIDEÓ"},
	{Name: "IrfanView", ID: "", Category: "GRAFIKA / KÉP / VIDEÓ"},
	{Name: "XnView", ID: "", Category: "GRAFIKA / KÉP / VIDEÓ"},
	{Name: "Inkscape", ID: "Inkscape.Inkscape", Category: "GRAFIKA / KÉP / VIDEÓ"},
	{Name: "FastStone Image Viewer", ID: "", Category: "GRAFIKA / KÉP / VIDEÓ"},
	{Name: "Greenshot", ID: "Greenshot.Greenshot", Category: "GRAFIKA / KÉP / VIDEÓ"},
	{Name: "ShareX", ID: "ShareX.ShareX", Category: "GRAFIKA / KÉP / VIDEÓ"},
	{Name: "OBS Studio", ID: "OBSProject.OBSStudio", Category: "GRAFIKA / KÉP / VIDEÓ"},
	{Name: "Foxit Reader", ID: "", Category: "DOKUMENTUMOK / PDF / IRODA"},
	{Name: "LibreOffice", ID: "TheDocumentFoundation.LibreOffice", Category: "DOKUMENTUMOK / PDF / IRODA"},
	{Name: "SumatraPDF", ID: "SumatraPDF.SumatraPDF", Category: "DOKUMENTUMOK / PDF / IRODA"},
	{Name: "CutePDF", ID: "", Category: "DOKUMENTUMOK / PDF / IRODA"},
	{Name: "OpenOffice", ID: "", Category: "DOKUMENTUMOK / PDF / IRODA"},
	{Name: "Adobe Acrobat Reader", ID: "", Category: "DOKUMENTUMOK / PDF / IRODA"},
	{Name: "Malwarebytes", ID: "Malwarebytes.Malwarebytes", Category: "BIZTONSÁG"},
	{Name: "Avast", ID: "", Category: "BIZTONSÁG"},
	{Name: "AVG", ID: "", Category: "BIZTONSÁG"},
	{Name: "Spybot 2", ID: "", Category: "BIZTONSÁG"},
	{Name: "Avira", ID: "", Category: "BIZTONSÁG"},
	{Name: "SUPERAntiSpyware", ID: "", Category: "BIZTONSÁG"},
	{Name: "qBittorrent", ID: "qBittorrent.qBittorrent", Category: "FÁJLMEGOSZTÁS / TORRENT"},
	{Name: "Dropbox", ID: "Dropbox.Dropbox", Category: "FELHŐ / SZINKRONIZÁLÁS"},
	{Name: "Google Drive for Desktop", ID: "Google.GoogleDrive", Category: "FELHŐ / SZINKRONIZÁLÁS"},
	{Name: "Microsoft OneDrive", ID: "Microsoft.OneDrive", Category: "FELHŐ / SZINKRONIZÁLÁS"},
	{Name: "SugarSync", ID: "", Category: "FELHŐ / SZINKRONIZÁLÁS"},
	{Name: "Steam", ID: "Valve.Steam", Category: "JÁTÉK / ÁLTALÁNOS"},
	{Name: "Epic Games Launcher", ID: "EpicGames.EpicGamesLauncher", Category: "JÁTÉK / ÁLTALÁNOS"},
	{Name: "Evernote", ID: "", Category: "JÁTÉK / ÁLTALÁNOS"},
	{Name: "Google Earth", ID: "", Category: "JÁTÉK / ÁLTALÁNOS"},
	{Name: "KeePass 2", ID: "DominikReichl.KeePass", Category: "JÁTÉK / ÁLTALÁNOS"},
	{Name: "Everything", ID: "voidtools.Everything", Category: "JÁTÉK / ÁLTALÁNOS"},
	{Name: "NV Access", ID: "", Category: "JÁTÉK / ÁLTALÁNOS"},
	{Name: "AnyDesk", ID: "", Category: "SEGÉDPROGRAMOK"},
	{Name: "TeamViewer 15", ID: "", Category: "SEGÉDPROGRAMOK"},
	{Name: "ImgBurn", ID: "", Category: "SEGÉDPROGRAMOK"},
	{Name: "RealVNC Server", ID: "", Category: "SEGÉDPROGRAMOK"},
	{Name: "RealVNC Viewer", ID: "", Category: "SEGÉDPROGRAMOK"},
	{Name: "TightVNC", ID: "", Category: "SEGÉDPROGRAMOK"},
	{Name: "TeraCopy", ID: "", Category: "SEGÉDPROGRAMOK"},
	{Name: "CDBurnerXP", ID: "", Category: "SEGÉDPROGRAMOK"},
	{Name: "Revo Uninstaller", ID: "", Category: "SEGÉDPROGRAMOK"},
	{Name: "Launchy", ID: "", Category: "SEGÉDPROGRAMOK"},
	{Name: "WinDirStat", ID: "WinDirStat.WinDirStat", Category: "SEGÉDPROGRAMOK"},
	{Name: "WizTree", ID: "", Category: "SEGÉDPROGRAMOK"},
	{Name: "Glary Utilities", ID: "", Category: "SEGÉDPROGRAMOK"},
	{Name: "InfraRecorder", ID: "", Category: "SEGÉDPROGRAMOK"},
	{Name: "Open-Shell", ID: "", Category: "SEGÉDPROGRAMOK"},
	{Name: "CCleaner", ID: "Piriform.CCleaner", Category: "SEGÉDPROGRAMOK"},
	{Name: "Microsoft PowerToys", ID: "Microsoft.PowerToys", Category: "SEGÉDPROGRAMOK"},
	{Name: "Rufus", ID: "Rufus.Rufus", Category: "SEGÉDPROGRAMOK"},
	{Name: "balenaEtcher", ID: "Balena.Etcher", Category: "SEGÉDPROGRAMOK"},
	{Name: "TreeSize Free", ID: "", Category: "SEGÉDPROGRAMOK"},
	{Name: "Windows Terminal", ID: "Microsoft.WindowsTerminal", Category: "SEGÉDPROGRAMOK"},
	{Name: "7-Zip", ID: "7zip.7zip", Category: "TÖMÖRÍTÉS"},
	{Name: "PeaZip", ID: "Giorgiotani.Peazip", Category: "TÖMÖRÍTÉS"},
	{Name: "WinRAR", ID: "", Category: "TÖMÖRÍTÉS"},
	{Name: "Python 3", ID: "Python.Python.3.13", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Python 2 / Legacy Python", ID: "", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Git", ID: "Git.Git", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "GitHub Desktop", ID: "GitHub.GitHubDesktop", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Node.js", ID: "OpenJS.NodeJS.LTS", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "FileZilla", ID: "", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Notepad++", ID: "Notepad++.Notepad++", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "WinSCP", ID: "WinSCP.WinSCP", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "PuTTY", ID: "PuTTY.PuTTY", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "WinMerge", ID: "", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Eclipse", ID: "", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Visual Studio Code", ID: "Microsoft.VisualStudioCode", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Cursor", ID: "Anysphere.Cursor", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Docker Desktop", ID: "", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Postman", ID: "Postman.Postman", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "DBeaver", ID: "DBeaver.DBeaver.Community", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "MySQL Workbench", ID: "", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Visual Studio Community", ID: "Microsoft.VisualStudio.2022.Community", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "IntelliJ IDEA Community", ID: "JetBrains.IntelliJIDEA.Community", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Android Studio", ID: "Google.AndroidStudio", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "GitKraken", ID: "Axosoft.GitKraken", Category: "FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Adoptium / AdoptOpenJDK JDK 8", ID: "", Category: "JAVA / JDK / JRE"},
	{Name: "Adoptium / AdoptOpenJDK JDK 11", ID: "", Category: "JAVA / JDK / JRE"},
	{Name: "Adoptium / AdoptOpenJDK JDK 17", ID: "", Category: "JAVA / JDK / JRE"},
	{Name: "Adoptium / AdoptOpenJDK JDK 21", ID: "", Category: "JAVA / JDK / JRE"},
	{Name: "Adoptium / AdoptOpenJDK JDK 25", ID: "", Category: "JAVA / JDK / JRE"},
	{Name: "Amazon Corretto JDK 8", ID: "", Category: "JAVA / JDK / JRE"},
	{Name: "Amazon Corretto JDK 11", ID: "", Category: "JAVA / JDK / JRE"},
	{Name: "Amazon Corretto JDK 17", ID: "", Category: "JAVA / JDK / JRE"},
	{Name: "Amazon Corretto JDK 21", ID: "", Category: "JAVA / JDK / JRE"},
	{Name: "Amazon Corretto JDK 25", ID: "", Category: "JAVA / JDK / JRE"},
	{Name: "Amazon Corretto JRE 8", ID: "", Category: "JAVA / JDK / JRE"},
	{Name: ".NET Framework 4.8.1", ID: "", Category: ".NET RUNTIME-OK"},
	{Name: ".NET Desktop Runtime 8", ID: "", Category: ".NET RUNTIME-OK"},
	{Name: ".NET Desktop Runtime 9", ID: "", Category: ".NET RUNTIME-OK"},
	{Name: ".NET Desktop Runtime 10", ID: "", Category: ".NET RUNTIME-OK"},
	{Name: "ASP.NET Core Runtime 8", ID: "", Category: ".NET RUNTIME-OK"},
	{Name: "ASP.NET Core Runtime 9", ID: "", Category: ".NET RUNTIME-OK"},
	{Name: "ASP.NET Core Runtime 10", ID: "", Category: ".NET RUNTIME-OK"},
	{Name: "Microsoft Visual C++ Redistributable 2015+", ID: "", Category: "MICROSOFT VISUAL C++ REDISTRIBUTABLE"},
	{Name: "Microsoft Visual C++ Redistributable 2013", ID: "", Category: "MICROSOFT VISUAL C++ REDISTRIBUTABLE"},
	{Name: "Microsoft Visual C++ Redistributable 2012", ID: "", Category: "MICROSOFT VISUAL C++ REDISTRIBUTABLE"},
	{Name: "Microsoft Visual C++ Redistributable 2010", ID: "", Category: "MICROSOFT VISUAL C++ REDISTRIBUTABLE"},
	{Name: "Microsoft Visual C++ Redistributable 2008", ID: "", Category: "MICROSOFT VISUAL C++ REDISTRIBUTABLE"},
	{Name: "Microsoft Visual C++ Redistributable 2005", ID: "", Category: "MICROSOFT VISUAL C++ REDISTRIBUTABLE"},
	{Name: "CPU-Z", ID: "", Category: "RENDSZERINFORMÁCIÓ / HARDVER / TESZT"},
	{Name: "HWiNFO", ID: "", Category: "RENDSZERINFORMÁCIÓ / HARDVER / TESZT"},
	{Name: "CrystalDiskInfo", ID: "", Category: "RENDSZERINFORMÁCIÓ / HARDVER / TESZT"},
	{Name: "CrystalDiskMark", ID: "", Category: "RENDSZERINFORMÁCIÓ / HARDVER / TESZT"},
	{Name: "FanControl", ID: "", Category: "RENDSZERINFORMÁCIÓ / HARDVER / TESZT"},
	{Name: "MSI Afterburner", ID: "", Category: "RENDSZERINFORMÁCIÓ / HARDVER / TESZT"},
	{Name: "iLok License Manager", ID: "", Category: "AUDIO / ZENE / HANGSZER"},
	{Name: "Focusrite Control 2", ID: "", Category: "AUDIO / ZENE / HANGSZER"},
	{Name: "Softube Central", ID: "", Category: "AUDIO / ZENE / HANGSZER"},
	{Name: "Amped Roots Free", ID: "", Category: "AUDIO / ZENE / HANGSZER"},
	{Name: "Neural Amp Modeler", ID: "", Category: "AUDIO / ZENE / HANGSZER"},
	{Name: "Tonocracy", ID: "", Category: "AUDIO / ZENE / HANGSZER"},
	{Name: "TDR Nova", ID: "", Category: "AUDIO / ZENE / HANGSZER"},
	{Name: "Vital", ID: "", Category: "AUDIO / ZENE / HANGSZER"},
	{Name: "Spitfire LABS", ID: "", Category: "AUDIO / ZENE / HANGSZER"},
	{Name: "ASIO4ALL", ID: "", Category: "AUDIO / ZENE / HANGSZER"},
	{Name: "REAPER", ID: "", Category: "AUDIO / ZENE / HANGSZER"},
	{Name: "FL Studio", ID: "", Category: "AUDIO / ZENE / HANGSZER"},
	{Name: "Cubase", ID: "", Category: "AUDIO / ZENE / HANGSZER"},
	{Name: "Archetype: Gojira X", ID: "", Category: "AUDIO / ZENE / HANGSZER"},
	{Name: "Unity Hub", ID: "", Category: "GAME DEVELOPMENT / 3D"},
	{Name: "Unity Editor / Unity Personal", ID: "", Category: "GAME DEVELOPMENT / 3D"},
	{Name: "Unreal Engine", ID: "", Category: "GAME DEVELOPMENT / 3D"},
	{Name: "Godot Engine", ID: "GodotEngine.GodotEngine", Category: "GAME DEVELOPMENT / 3D"},
	{Name: "CMake", ID: "Kitware.CMake", Category: "FEJLESZTÉS"},
	{Name: "Cisco Packet Tracer", ID: "", Category: "HÁLÓZAT / IT / LABOR"},
	{Name: "Wireshark", ID: "WiresharkFoundation.Wireshark", Category: "HÁLÓZAT / IT / LABOR"},
	{Name: "Nmap", ID: "Insecure.Nmap", Category: "HÁLÓZAT / IT / LABOR"},
	{Name: "VirtualBox", ID: "Oracle.VirtualBox", Category: "HÁLÓZAT / IT / LABOR"},
	{Name: "VMware Workstation", ID: "", Category: "HÁLÓZAT / IT / LABOR"},
	{Name: "Ventoy", ID: "Ventoy.Ventoy", Category: "HÁLÓZAT / IT / LABOR"},
	{Name: "Pentablet driver / kezelőszoftver", ID: "", Category: "HARDVER / PERIFÉRIA"},
	{Name: "Microsoft Word", ID: "", Category: "MICROSOFT OFFICE / FIZETŐS ALKALMAZÁSOK"},
	{Name: "Microsoft Excel", ID: "", Category: "MICROSOFT OFFICE / FIZETŐS ALKALMAZÁSOK"},
	{Name: "Microsoft PowerPoint", ID: "", Category: "MICROSOFT OFFICE / FIZETŐS ALKALMAZÁSOK"},
	{Name: "Microsoft Access", ID: "", Category: "MICROSOFT OFFICE / FIZETŐS ALKALMAZÁSOK"},
	{Name: "GOG GALAXY", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "EA app", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "Ubisoft Connect", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "Battle.net", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "Riot Client", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "Rockstar Games Launcher", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "itch.io App", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "Amazon Games App", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "Xbox App", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "Minecraft Launcher", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "Prism Launcher", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "MultiMC", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "CurseForge", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "Modrinth App", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "Nexus Mods / Vortex", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "Overwolf", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "Playnite", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "Heroic Games Launcher", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "Lutris", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "GeForce NOW", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "Moonlight", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "Sunshine", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "Parsec", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "Antstream Arcade", ID: "", Category: "JÁTÉKPLATFORMOK / LAUNCHEREK"},
	{Name: "LogMeIn Hamachi", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "Tailscale", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "ZeroTier", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "WireGuard", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "OpenVPN Connect", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "SoftEther VPN Client", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "Proton VPN", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "Mullvad VPN", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "Windscribe", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "Cloudflare WARP", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "TunnelBear", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "NordVPN", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "Surfshark", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "Private Internet Access", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "NetBird", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "Headscale", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "Nebula", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "Radmin VPN", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "GameRanger", ID: "", Category: "VIRTUÁLIS HÁLÓZAT / VPN / LAN"},
	{Name: "TeamViewer", ID: "", Category: "TÁVOLI ELÉRÉS / REMOTE DESKTOP"},
	{Name: "RustDesk", ID: "", Category: "TÁVOLI ELÉRÉS / REMOTE DESKTOP"},
	{Name: "UltraVNC", ID: "", Category: "TÁVOLI ELÉRÉS / REMOTE DESKTOP"},
	{Name: "Chrome Remote Desktop", ID: "", Category: "TÁVOLI ELÉRÉS / REMOTE DESKTOP"},
	{Name: "Microsoft Remote Desktop", ID: "", Category: "TÁVOLI ELÉRÉS / REMOTE DESKTOP"},
	{Name: "mRemoteNG", ID: "", Category: "TÁVOLI ELÉRÉS / REMOTE DESKTOP"},
	{Name: "MobaXterm", ID: "", Category: "TÁVOLI ELÉRÉS / REMOTE DESKTOP"},
	{Name: "Termius", ID: "", Category: "TÁVOLI ELÉRÉS / REMOTE DESKTOP"},
	{Name: "NoMachine", ID: "", Category: "TÁVOLI ELÉRÉS / REMOTE DESKTOP"},
	{Name: "Splashtop", ID: "", Category: "TÁVOLI ELÉRÉS / REMOTE DESKTOP"},
	{Name: "DWService", ID: "", Category: "TÁVOLI ELÉRÉS / REMOTE DESKTOP"},
	{Name: "Ollama", ID: "Ollama.Ollama", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "LM Studio", ID: "ElementLabs.LMStudio", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "Jan", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "GPT4All", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "AnythingLLM", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "Open WebUI", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "llama.cpp", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "KoboldCpp", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "text-generation-webui", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "LocalAI", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "vLLM", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "OpenLLM", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "Pinokio", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "Open Interpreter", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "Continue", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "Aider", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "Cline", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "Roo Code", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "Claude Code", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "Codex CLI", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "OpenHands", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "Dify", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "Flowise", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "Langflow", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "AnythingLLM Desktop", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "PrivateGPT", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "Chatbox", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "Msty", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "Cherry Studio", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "Perplexica", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "Khoj", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "LibreChat", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "SillyTavern", ID: "", Category: "LOKÁLIS AI / LLM / CHAT"},
	{Name: "ComfyUI", ID: "", Category: "AI KÉPGENERÁLÁS / STABLE DIFFUSION"},
	{Name: "AUTOMATIC1111 Stable Diffusion WebUI", ID: "", Category: "AI KÉPGENERÁLÁS / STABLE DIFFUSION"},
	{Name: "Forge WebUI", ID: "", Category: "AI KÉPGENERÁLÁS / STABLE DIFFUSION"},
	{Name: "Fooocus", ID: "", Category: "AI KÉPGENERÁLÁS / STABLE DIFFUSION"},
	{Name: "InvokeAI", ID: "", Category: "AI KÉPGENERÁLÁS / STABLE DIFFUSION"},
	{Name: "SwarmUI", ID: "", Category: "AI KÉPGENERÁLÁS / STABLE DIFFUSION"},
	{Name: "DiffusionBee", ID: "", Category: "AI KÉPGENERÁLÁS / STABLE DIFFUSION"},
	{Name: "Stable Diffusion WebUI Forge", ID: "", Category: "AI KÉPGENERÁLÁS / STABLE DIFFUSION"},
	{Name: "Easy Diffusion", ID: "", Category: "AI KÉPGENERÁLÁS / STABLE DIFFUSION"},
	{Name: "Krita AI Diffusion plugin", ID: "", Category: "AI KÉPGENERÁLÁS / STABLE DIFFUSION"},
	{Name: "Draw Things", ID: "", Category: "AI KÉPGENERÁLÁS / STABLE DIFFUSION"},
	{Name: "Upscayl", ID: "", Category: "AI KÉPGENERÁLÁS / STABLE DIFFUSION"},
	{Name: "Real-ESRGAN", ID: "", Category: "AI KÉPGENERÁLÁS / STABLE DIFFUSION"},
	{Name: "Topaz Photo AI", ID: "", Category: "AI KÉPGENERÁLÁS / STABLE DIFFUSION"},
	{Name: "Topaz Gigapixel AI", ID: "", Category: "AI KÉPGENERÁLÁS / STABLE DIFFUSION"},
	{Name: "Windsurf", ID: "", Category: "AI FEJLESZTŐI ESZKÖZÖK"},
	{Name: "GitHub Copilot", ID: "", Category: "AI FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Tabby", ID: "", Category: "AI FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Sourcegraph Cody", ID: "", Category: "AI FEJLESZTŐI ESZKÖZÖK"},
	{Name: "JetBrains AI Assistant", ID: "", Category: "AI FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Amazon Q Developer", ID: "", Category: "AI FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Pieces for Developers", ID: "", Category: "AI FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Codeium / Windsurf plugin", ID: "", Category: "AI FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Continue.dev", ID: "", Category: "AI FEJLESZTŐI ESZKÖZÖK"},
	{Name: "Tabnine", ID: "", Category: "AI FEJLESZTŐI ESZKÖZÖK"},
	{Name: "XAMPP", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "WampServer", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "Laragon", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "MAMP", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "LocalWP", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "DDEV", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "Devilbox", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "Lando", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "Podman Desktop", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "Rancher Desktop", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "WSL", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "WSL2", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "Apache HTTP Server", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "Nginx", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "Caddy", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "IIS Express", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "PHP", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "Composer", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "npm", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "pnpm", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "Yarn", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "Bun", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "Deno", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "Python", ID: "Python.Python.3.13", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "pip", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "Ruby", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "Ruby on Rails", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "Go", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "Rust", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "Java JDK", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: ".NET SDK", ID: "", Category: "WEBFEJLESZTŐI STACK / LOKÁLIS SZERVER"},
	{Name: "MySQL", ID: "", Category: "ADATBÁZIS SZERVEREK"},
	{Name: "MariaDB", ID: "", Category: "ADATBÁZIS SZERVEREK"},
	{Name: "PostgreSQL", ID: "", Category: "ADATBÁZIS SZERVEREK"},
	{Name: "SQLite", ID: "", Category: "ADATBÁZIS SZERVEREK"},
	{Name: "MongoDB Community Server", ID: "", Category: "ADATBÁZIS SZERVEREK"},
	{Name: "Redis", ID: "", Category: "ADATBÁZIS SZERVEREK"},
	{Name: "Memcached", ID: "", Category: "ADATBÁZIS SZERVEREK"},
	{Name: "Microsoft SQL Server Express", ID: "", Category: "ADATBÁZIS SZERVEREK"},
	{Name: "Microsoft SQL Server Developer", ID: "", Category: "ADATBÁZIS SZERVEREK"},
	{Name: "Oracle Database Free", ID: "", Category: "ADATBÁZIS SZERVEREK"},
	{Name: "CockroachDB", ID: "", Category: "ADATBÁZIS SZERVEREK"},
	{Name: "CouchDB", ID: "", Category: "ADATBÁZIS SZERVEREK"},
	{Name: "Neo4j Community", ID: "", Category: "ADATBÁZIS SZERVEREK"},
	{Name: "InfluxDB", ID: "", Category: "ADATBÁZIS SZERVEREK"},
	{Name: "TimescaleDB", ID: "", Category: "ADATBÁZIS SZERVEREK"},
	{Name: "ClickHouse", ID: "", Category: "ADATBÁZIS SZERVEREK"},
	{Name: "DuckDB", ID: "", Category: "ADATBÁZIS SZERVEREK"},
	{Name: "HeidiSQL", ID: "", Category: "ADATBÁZIS KEZELŐK / SQL GUI"},
	{Name: "pgAdmin", ID: "", Category: "ADATBÁZIS KEZELŐK / SQL GUI"},
	{Name: "SQL Server Management Studio", ID: "", Category: "ADATBÁZIS KEZELŐK / SQL GUI"},
	{Name: "Azure Data Studio", ID: "", Category: "ADATBÁZIS KEZELŐK / SQL GUI"},
	{Name: "SQLiteStudio", ID: "", Category: "ADATBÁZIS KEZELŐK / SQL GUI"},
	{Name: "DB Browser for SQLite", ID: "", Category: "ADATBÁZIS KEZELŐK / SQL GUI"},
	{Name: "MongoDB Compass", ID: "", Category: "ADATBÁZIS KEZELŐK / SQL GUI"},
	{Name: "RedisInsight", ID: "", Category: "ADATBÁZIS KEZELŐK / SQL GUI"},
	{Name: "JetBrains DataGrip", ID: "", Category: "ADATBÁZIS KEZELŐK / SQL GUI"},
	{Name: "TablePlus", ID: "", Category: "ADATBÁZIS KEZELŐK / SQL GUI"},
	{Name: "Beekeeper Studio", ID: "", Category: "ADATBÁZIS KEZELŐK / SQL GUI"},
	{Name: "Navicat", ID: "", Category: "ADATBÁZIS KEZELŐK / SQL GUI"},
	{Name: "DbGate", ID: "", Category: "ADATBÁZIS KEZELŐK / SQL GUI"},
	{Name: "RazorSQL", ID: "", Category: "ADATBÁZIS KEZELŐK / SQL GUI"},
	{Name: "SQuirreL SQL", ID: "", Category: "ADATBÁZIS KEZELŐK / SQL GUI"},
	{Name: "Adminer", ID: "", Category: "ADATBÁZIS KEZELŐK / SQL GUI"},
	{Name: "phpMyAdmin", ID: "", Category: "ADATBÁZIS KEZELŐK / SQL GUI"},
	{Name: "Insomnia", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "Bruno", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "Hoppscotch", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "HTTPie", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "curl", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "wget", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "SoapUI", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "Fiddler Classic", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "Fiddler Everywhere", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "Charles Proxy", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "mitmproxy", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "Burp Suite Community Edition", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "OWASP ZAP", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "k6", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "Apache JMeter", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "Locust", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "Swagger Editor", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "Swagger UI", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "Stoplight Studio", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "Yaak", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "Paw / RapidAPI Client", ID: "", Category: "API / BACKEND / TESZTELÉS"},
	{Name: "VSCodium", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "Visual Studio Professional", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "Visual Studio Enterprise", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "Sublime Text", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "Zed", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "Eclipse IDE", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "Apache NetBeans", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "Code::Blocks", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "Geany", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "Kate", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "Lite XL", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "Neovim", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "Vim", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "Emacs", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "Lapce", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "Helix", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "Pulsar", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "Nova", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "TextMate", ID: "", Category: "IDE-K / KÓDSZERKESZTŐK"},
	{Name: "JetBrains Toolbox App", ID: "JetBrains.Toolbox", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "IntelliJ IDEA Ultimate", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "PyCharm Community", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "PyCharm Professional", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "WebStorm", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "PhpStorm", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "Rider", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "CLion", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "DataGrip", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "GoLand", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "RubyMine", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "RustRover", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "DataSpell", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "Aqua", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "Fleet", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "ReSharper", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "ReSharper C++", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "dotPeek", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "dotCover", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "dotTrace", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "dotMemory", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "TeamCity", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "YouTrack", ID: "", Category: "JETBRAINS IDE-K / ESZKÖZÖK"},
	{Name: "Fork", ID: "", Category: "VERZIÓKEZELÉS / GIT"},
	{Name: "Sourcetree", ID: "", Category: "VERZIÓKEZELÉS / GIT"},
	{Name: "TortoiseGit", ID: "", Category: "VERZIÓKEZELÉS / GIT"},
	{Name: "TortoiseSVN", ID: "", Category: "VERZIÓKEZELÉS / GIT"},
	{Name: "Git Extensions", ID: "", Category: "VERZIÓKEZELÉS / GIT"},
	{Name: "Lazygit", ID: "", Category: "VERZIÓKEZELÉS / GIT"},
	{Name: "GitHub CLI", ID: "GitHub.cli", Category: "VERZIÓKEZELÉS / GIT"},
	{Name: "GitLab CLI", ID: "", Category: "VERZIÓKEZELÉS / GIT"},
	{Name: "Gitea", ID: "", Category: "VERZIÓKEZELÉS / GIT"},
	{Name: "Gitea Actions runner", ID: "", Category: "VERZIÓKEZELÉS / GIT"},
	{Name: "SmartGit", ID: "", Category: "VERZIÓKEZELÉS / GIT"},
	{Name: "Tower", ID: "", Category: "VERZIÓKEZELÉS / GIT"},
	{Name: "Sublime Merge", ID: "", Category: "VERZIÓKEZELÉS / GIT"},
	{Name: "Plastic SCM / Unity Version Control", ID: "", Category: "VERZIÓKEZELÉS / GIT"},
	{Name: "Photopea", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Clip Studio Paint", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Corel Painter", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "MediBang Paint", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "FireAlpaca", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Affinity Photo", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Affinity Designer", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Affinity Publisher", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Adobe Photoshop", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Adobe Illustrator", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Adobe Lightroom", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Adobe Fresco", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Adobe Creative Cloud", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Sketchbook", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "ArtRage", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Rebelle", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "PaintTool SAI", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "MyPaint", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Pinta", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Concepts", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "ibis Paint", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Leonardo", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Kleki", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Pixlr", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Fotor", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Canva Desktop", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "PhotoScape X", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "PhotoFiltre", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "PhotoDemon", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "LazPaint", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Krita Gemini / kapcsolódó Krita eszközök", ID: "", Category: "GRAFIKA / DIGITÁLIS RAJZ"},
	{Name: "Aseprite", ID: "", Category: "PIXEL ART / SPRITE / 2D GAME ART"},
	{Name: "LibreSprite", ID: "", Category: "PIXEL ART / SPRITE / 2D GAME ART"},
	{Name: "Pixelorama", ID: "", Category: "PIXEL ART / SPRITE / 2D GAME ART"},
	{Name: "Piskel", ID: "", Category: "PIXEL ART / SPRITE / 2D GAME ART"},
	{Name: "GraphicsGale", ID: "", Category: "PIXEL ART / SPRITE / 2D GAME ART"},
	{Name: "Pyxel Edit", ID: "", Category: "PIXEL ART / SPRITE / 2D GAME ART"},
	{Name: "Pro Motion NG", ID: "", Category: "PIXEL ART / SPRITE / 2D GAME ART"},
	{Name: "Tilesetter", ID: "", Category: "PIXEL ART / SPRITE / 2D GAME ART"},
	{Name: "Tiled Map Editor", ID: "", Category: "PIXEL ART / SPRITE / 2D GAME ART"},
	{Name: "LDtk", ID: "", Category: "PIXEL ART / SPRITE / 2D GAME ART"},
	{Name: "TexturePacker", ID: "", Category: "PIXEL ART / SPRITE / 2D GAME ART"},
	{Name: "Shoebox", ID: "", Category: "PIXEL ART / SPRITE / 2D GAME ART"},
	{Name: "SpriteIlluminator", ID: "", Category: "PIXEL ART / SPRITE / 2D GAME ART"},
	{Name: "Ogmo Editor", ID: "", Category: "PIXEL ART / SPRITE / 2D GAME ART"},
	{Name: "CrocoTile 3D", ID: "", Category: "PIXEL ART / SPRITE / 2D GAME ART"},
	{Name: "PixelOver", ID: "", Category: "PIXEL ART / SPRITE / 2D GAME ART"},
	{Name: "Resprite", ID: "", Category: "PIXEL ART / SPRITE / 2D GAME ART"},
	{Name: "Lospec Pixel Editor", ID: "", Category: "PIXEL ART / SPRITE / 2D GAME ART"},
	{Name: "FreeCAD", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "OpenSCAD", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "SketchUp", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "Autodesk Fusion", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "Autodesk Maya", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "Autodesk 3ds Max", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "Cinema 4D", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "ZBrush", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "Nomad Sculpt", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "MeshLab", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "Meshmixer", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "Substance 3D Painter", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "Substance 3D Designer", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "Marvelous Designer", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "Houdini", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "Rhino", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "Solid Edge Community Edition", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "SolveSpace", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "BRL-CAD", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "Wings 3D", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "MagicaVoxel", ID: "", Category: "3D / MODELLEZÉS / CAD"},
	{Name: "Unity Editor", ID: "", Category: "GAME DEVELOPMENT"},
	{Name: "GameMaker", ID: "", Category: "GAME DEVELOPMENT"},
	{Name: "Construct 3", ID: "", Category: "GAME DEVELOPMENT"},
	{Name: "GDevelop", ID: "", Category: "GAME DEVELOPMENT"},
	{Name: "Defold", ID: "", Category: "GAME DEVELOPMENT"},
	{Name: "RPG Maker", ID: "", Category: "GAME DEVELOPMENT"},
	{Name: "Ren'Py", ID: "", Category: "GAME DEVELOPMENT"},
	{Name: "MonoGame", ID: "", Category: "GAME DEVELOPMENT"},
	{Name: "Cocos Creator", ID: "", Category: "GAME DEVELOPMENT"},
	{Name: "CryEngine", ID: "", Category: "GAME DEVELOPMENT"},
	{Name: "Stride", ID: "", Category: "GAME DEVELOPMENT"},
	{Name: "Panda3D", ID: "", Category: "GAME DEVELOPMENT"},
	{Name: "Love2D", ID: "", Category: "GAME DEVELOPMENT"},
	{Name: "darktable", ID: "", Category: "FOTÓ / RAW / KÉPKEZELÉS"},
	{Name: "RawTherapee", ID: "", Category: "FOTÓ / RAW / KÉPKEZELÉS"},
	{Name: "digiKam", ID: "", Category: "FOTÓ / RAW / KÉPKEZELÉS"},
	{Name: "XnView MP", ID: "", Category: "FOTÓ / RAW / KÉPKEZELÉS"},
	{Name: "ImageGlass", ID: "", Category: "FOTÓ / RAW / KÉPKEZELÉS"},
	{Name: "nomacs", ID: "", Category: "FOTÓ / RAW / KÉPKEZELÉS"},
	{Name: "JPEGView", ID: "", Category: "FOTÓ / RAW / KÉPKEZELÉS"},
	{Name: "ExifTool", ID: "", Category: "FOTÓ / RAW / KÉPKEZELÉS"},
	{Name: "Hugin", ID: "", Category: "FOTÓ / RAW / KÉPKEZELÉS"},
	{Name: "Luminance HDR", ID: "", Category: "FOTÓ / RAW / KÉPKEZELÉS"},
	{Name: "Photivo", ID: "", Category: "FOTÓ / RAW / KÉPKEZELÉS"},
	{Name: "Capture One", ID: "", Category: "FOTÓ / RAW / KÉPKEZELÉS"},
	{Name: "ON1 Photo RAW", ID: "", Category: "FOTÓ / RAW / KÉPKEZELÉS"},
	{Name: "ACDSee Photo Studio", ID: "", Category: "FOTÓ / RAW / KÉPKEZELÉS"},
	{Name: "Luminar Neo", ID: "", Category: "FOTÓ / RAW / KÉPKEZELÉS"},
	{Name: "Flameshot", ID: "", Category: "SCREENSHOT / KÉPERNYŐRÖGZÍTÉS / STREAM"},
	{Name: "Lightshot", ID: "", Category: "SCREENSHOT / KÉPERNYŐRÖGZÍTÉS / STREAM"},
	{Name: "Snipping Tool", ID: "", Category: "SCREENSHOT / KÉPERNYŐRÖGZÍTÉS / STREAM"},
	{Name: "Streamlabs Desktop", ID: "", Category: "SCREENSHOT / KÉPERNYŐRÖGZÍTÉS / STREAM"},
	{Name: "Bandicam", ID: "", Category: "SCREENSHOT / KÉPERNYŐRÖGZÍTÉS / STREAM"},
	{Name: "Camtasia", ID: "", Category: "SCREENSHOT / KÉPERNYŐRÖGZÍTÉS / STREAM"},
	{Name: "ScreenToGif", ID: "", Category: "SCREENSHOT / KÉPERNYŐRÖGZÍTÉS / STREAM"},
	{Name: "Gyazo", ID: "", Category: "SCREENSHOT / KÉPERNYŐRÖGZÍTÉS / STREAM"},
	{Name: "LICEcap", ID: "", Category: "SCREENSHOT / KÉPERNYŐRÖGZÍTÉS / STREAM"},
	{Name: "NVIDIA App / ShadowPlay", ID: "", Category: "SCREENSHOT / KÉPERNYŐRÖGZÍTÉS / STREAM"},
	{Name: "AMD Software Adrenalin Recording", ID: "", Category: "SCREENSHOT / KÉPERNYŐRÖGZÍTÉS / STREAM"},
	{Name: "Xbox Game Bar", ID: "", Category: "SCREENSHOT / KÉPERNYŐRÖGZÍTÉS / STREAM"},
	{Name: "Action!", ID: "", Category: "SCREENSHOT / KÉPERNYŐRÖGZÍTÉS / STREAM"},
	{Name: "XSplit Broadcaster", ID: "", Category: "SCREENSHOT / KÉPERNYŐRÖGZÍTÉS / STREAM"},
	{Name: "Elgato 4K Capture Utility", ID: "", Category: "SCREENSHOT / KÉPERNYŐRÖGZÍTÉS / STREAM"},
	{Name: "Elgato Stream Deck", ID: "", Category: "SCREENSHOT / KÉPERNYŐRÖGZÍTÉS / STREAM"},
	{Name: "DaVinci Resolve", ID: "", Category: "VIDEÓVÁGÁS / KONVERTÁLÁS"},
	{Name: "Kdenlive", ID: "KDE.Kdenlive", Category: "VIDEÓVÁGÁS / KONVERTÁLÁS"},
	{Name: "Shotcut", ID: "Meltytech.Shotcut", Category: "VIDEÓVÁGÁS / KONVERTÁLÁS"},
	{Name: "OpenShot", ID: "OpenShot.OpenShot", Category: "VIDEÓVÁGÁS / KONVERTÁLÁS"},
	{Name: "FFmpeg", ID: "Gyan.FFmpeg", Category: "VIDEÓVÁGÁS / KONVERTÁLÁS"},
	{Name: "Avidemux", ID: "", Category: "VIDEÓVÁGÁS / KONVERTÁLÁS"},
	{Name: "LosslessCut", ID: "", Category: "VIDEÓVÁGÁS / KONVERTÁLÁS"},
	{Name: "Shutter Encoder", ID: "", Category: "VIDEÓVÁGÁS / KONVERTÁLÁS"},
	{Name: "CapCut Desktop", ID: "", Category: "VIDEÓVÁGÁS / KONVERTÁLÁS"},
	{Name: "VEGAS Pro", ID: "", Category: "VIDEÓVÁGÁS / KONVERTÁLÁS"},
	{Name: "Adobe Premiere Pro", ID: "", Category: "VIDEÓVÁGÁS / KONVERTÁLÁS"},
	{Name: "Adobe After Effects", ID: "", Category: "VIDEÓVÁGÁS / KONVERTÁLÁS"},
	{Name: "HitFilm", ID: "", Category: "VIDEÓVÁGÁS / KONVERTÁLÁS"},
	{Name: "Lightworks", ID: "", Category: "VIDEÓVÁGÁS / KONVERTÁLÁS"},
	{Name: "Olive Video Editor", ID: "", Category: "VIDEÓVÁGÁS / KONVERTÁLÁS"},
	{Name: "VSDC Free Video Editor", ID: "", Category: "VIDEÓVÁGÁS / KONVERTÁLÁS"},
	{Name: "Filmora", ID: "", Category: "VIDEÓVÁGÁS / KONVERTÁLÁS"},
	{Name: "Ableton Live", ID: "", Category: "AUDIO / ZENE / DAW"},
	{Name: "Studio One", ID: "", Category: "AUDIO / ZENE / DAW"},
	{Name: "Cakewalk", ID: "", Category: "AUDIO / ZENE / DAW"},
	{Name: "Waveform Free", ID: "", Category: "AUDIO / ZENE / DAW"},
	{Name: "LMMS", ID: "", Category: "AUDIO / ZENE / DAW"},
	{Name: "Ardour", ID: "", Category: "AUDIO / ZENE / DAW"},
	{Name: "MuseScore", ID: "", Category: "AUDIO / ZENE / DAW"},
	{Name: "Equalizer APO", ID: "", Category: "AUDIO / ZENE / DAW"},
	{Name: "Peace Equalizer", ID: "", Category: "AUDIO / ZENE / DAW"},
	{Name: "Voicemeeter", ID: "", Category: "AUDIO / ZENE / DAW"},
	{Name: "VB-CABLE", ID: "", Category: "AUDIO / ZENE / DAW"},
	{Name: "Mixxx", ID: "", Category: "AUDIO / ZENE / DAW"},
	{Name: "Ocenaudio", ID: "", Category: "AUDIO / ZENE / DAW"},
	{Name: "Tenacity", ID: "", Category: "AUDIO / ZENE / DAW"},
	{Name: "Native Access", ID: "", Category: "GITÁR / AUDIO PLUGIN / HARDVER"},
	{Name: "IK Product Manager", ID: "", Category: "GITÁR / AUDIO PLUGIN / HARDVER"},
	{Name: "Arturia Software Center", ID: "", Category: "GITÁR / AUDIO PLUGIN / HARDVER"},
	{Name: "Waves Central", ID: "", Category: "GITÁR / AUDIO PLUGIN / HARDVER"},
	{Name: "Neural DSP", ID: "", Category: "GITÁR / AUDIO PLUGIN / HARDVER"},
	{Name: "AmpliTube", ID: "", Category: "GITÁR / AUDIO PLUGIN / HARDVER"},
	{Name: "Guitar Rig", ID: "", Category: "GITÁR / AUDIO PLUGIN / HARDVER"},
	{Name: "ToneX", ID: "", Category: "GITÁR / AUDIO PLUGIN / HARDVER"},
	{Name: "NAM Universal", ID: "", Category: "GITÁR / AUDIO PLUGIN / HARDVER"},
	{Name: "ReaPlugs", ID: "", Category: "GITÁR / AUDIO PLUGIN / HARDVER"},
	{Name: "Helix Native", ID: "", Category: "GITÁR / AUDIO PLUGIN / HARDVER"},
	{Name: "TH-U", ID: "", Category: "GITÁR / AUDIO PLUGIN / HARDVER"},
	{Name: "BIAS FX", ID: "", Category: "GITÁR / AUDIO PLUGIN / HARDVER"},
	{Name: "Positive Grid Spark app", ID: "", Category: "GITÁR / AUDIO PLUGIN / HARDVER"},
	{Name: "Line 6 Central", ID: "", Category: "GITÁR / AUDIO PLUGIN / HARDVER"},
	{Name: "Apache OpenOffice", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "Microsoft 365 / Office", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "OnlyOffice Desktop Editors", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "WPS Office", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "FreeOffice", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "PDF24 Creator", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "Foxit PDF Reader", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "Okular", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "Xournal++", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "Obsidian", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "Notion", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "Joplin", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "Logseq", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "Zotero", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "Mendeley Reference Manager", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "Typora", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "MarkText", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "Trilium Notes", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "Standard Notes", ID: "", Category: "OFFICE / PDF / JEGYZET"},
	{Name: "NanaZip", ID: "", Category: "FÁJLKEZELÉS / KERESÉS / TÖMÖRÍTÉS"},
	{Name: "Bandizip", ID: "", Category: "FÁJLKEZELÉS / KERESÉS / TÖMÖRÍTÉS"},
	{Name: "Listary", ID: "", Category: "FÁJLKEZELÉS / KERESÉS / TÖMÖRÍTÉS"},
	{Name: "Total Commander", ID: "", Category: "FÁJLKEZELÉS / KERESÉS / TÖMÖRÍTÉS"},
	{Name: "Double Commander", ID: "", Category: "FÁJLKEZELÉS / KERESÉS / TÖMÖRÍTÉS"},
	{Name: "FreeCommander", ID: "", Category: "FÁJLKEZELÉS / KERESÉS / TÖMÖRÍTÉS"},
	{Name: "Files App", ID: "", Category: "FÁJLKEZELÉS / KERESÉS / TÖMÖRÍTÉS"},
	{Name: "Directory Opus", ID: "", Category: "FÁJLKEZELÉS / KERESÉS / TÖMÖRÍTÉS"},
	{Name: "FastCopy", ID: "", Category: "FÁJLKEZELÉS / KERESÉS / TÖMÖRÍTÉS"},
	{Name: "Bulk Rename Utility", ID: "", Category: "FÁJLKEZELÉS / KERESÉS / TÖMÖRÍTÉS"},
	{Name: "SpaceSniffer", ID: "", Category: "FÁJLKEZELÉS / KERESÉS / TÖMÖRÍTÉS"},
	{Name: "OneCommander", ID: "", Category: "FÁJLKEZELÉS / KERESÉS / TÖMÖRÍTÉS"},
	{Name: "Sysinternals Suite", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "Process Explorer", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "Process Monitor", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "Autoruns", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "TCPView", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "GPU-Z", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "HWMonitor", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "Speccy", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "Hard Disk Sentinel", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "RivaTuner Statistics Server", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "OCCT", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "Prime95", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "Cinebench", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "MemTest86", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "Victoria HDD/SSD", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "AIDA64", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "Core Temp", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "Open Hardware Monitor", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "Libre Hardware Monitor", ID: "", Category: "RENDSZER / HARDVER / DIAGNOSZTIKA"},
	{Name: "UNetbootin", ID: "", Category: "WINDOWS TELEPÍTÉS / USB / ISO"},
	{Name: "YUMI", ID: "", Category: "WINDOWS TELEPÍTÉS / USB / ISO"},
	{Name: "Win32 Disk Imager", ID: "", Category: "WINDOWS TELEPÍTÉS / USB / ISO"},
	{Name: "PowerISO", ID: "", Category: "WINDOWS TELEPÍTÉS / USB / ISO"},
	{Name: "AnyBurn", ID: "", Category: "WINDOWS TELEPÍTÉS / USB / ISO"},
	{Name: "WinCDEmu", ID: "", Category: "WINDOWS TELEPÍTÉS / USB / ISO"},
	{Name: "Virtual CloneDrive", ID: "", Category: "WINDOWS TELEPÍTÉS / USB / ISO"},
	{Name: "Media Creation Tool", ID: "", Category: "WINDOWS TELEPÍTÉS / USB / ISO"},
	{Name: "Windows Installation Assistant", ID: "", Category: "WINDOWS TELEPÍTÉS / USB / ISO"},
	{Name: "NTLite", ID: "", Category: "WINDOWS TELEPÍTÉS / USB / ISO"},
	{Name: "Hyper-V", ID: "", Category: "VIRTUALIZÁCIÓ / KONTAINEREK"},
	{Name: "WSL2 disztribúciók", ID: "", Category: "VIRTUALIZÁCIÓ / KONTAINEREK"},
	{Name: "QEMU", ID: "", Category: "VIRTUALIZÁCIÓ / KONTAINEREK"},
	{Name: "Vagrant", ID: "", Category: "VIRTUALIZÁCIÓ / KONTAINEREK"},
	{Name: "Multipass", ID: "", Category: "VIRTUALIZÁCIÓ / KONTAINEREK"},
	{Name: "Minikube", ID: "", Category: "VIRTUALIZÁCIÓ / KONTAINEREK"},
	{Name: "Kubernetes kubectl", ID: "", Category: "VIRTUALIZÁCIÓ / KONTAINEREK"},
	{Name: "kind", ID: "", Category: "VIRTUALIZÁCIÓ / KONTAINEREK"},
	{Name: "k3d", ID: "", Category: "VIRTUALIZÁCIÓ / KONTAINEREK"},
	{Name: "Portainer Desktop / kapcsolódó kliensek", ID: "", Category: "VIRTUALIZÁCIÓ / KONTAINEREK"},
	{Name: "GNS3", ID: "", Category: "HÁLÓZATI / CISCO / IT ESZKÖZÖK"},
	{Name: "EVE-NG Client Pack", ID: "", Category: "HÁLÓZATI / CISCO / IT ESZKÖZÖK"},
	{Name: "KiTTY", ID: "", Category: "HÁLÓZATI / CISCO / IT ESZKÖZÖK"},
	{Name: "Angry IP Scanner", ID: "", Category: "HÁLÓZATI / CISCO / IT ESZKÖZÖK"},
	{Name: "Advanced IP Scanner", ID: "", Category: "HÁLÓZATI / CISCO / IT ESZKÖZÖK"},
	{Name: "PortQry", ID: "", Category: "HÁLÓZATI / CISCO / IT ESZKÖZÖK"},
	{Name: "iperf3", ID: "", Category: "HÁLÓZATI / CISCO / IT ESZKÖZÖK"},
	{Name: "OpenSpeedTest", ID: "", Category: "HÁLÓZATI / CISCO / IT ESZKÖZÖK"},
	{Name: "Netcat / Ncat", ID: "", Category: "HÁLÓZATI / CISCO / IT ESZKÖZÖK"},
	{Name: "Solar-PuTTY", ID: "", Category: "HÁLÓZATI / CISCO / IT ESZKÖZÖK"},
	{Name: "Bitvise SSH Client", ID: "", Category: "HÁLÓZATI / CISCO / IT ESZKÖZÖK"},
	{Name: "OpenSSH for Windows", ID: "", Category: "HÁLÓZATI / CISCO / IT ESZKÖZÖK"},
	{Name: "MEGA Desktop App", ID: "", Category: "FELHŐ / SZINKRONIZÁLÁS"},
	{Name: "Proton Drive", ID: "", Category: "FELHŐ / SZINKRONIZÁLÁS"},
	{Name: "pCloud Drive", ID: "", Category: "FELHŐ / SZINKRONIZÁLÁS"},
	{Name: "Nextcloud Desktop", ID: "", Category: "FELHŐ / SZINKRONIZÁLÁS"},
	{Name: "Syncthing", ID: "", Category: "FELHŐ / SZINKRONIZÁLÁS"},
	{Name: "Resilio Sync", ID: "", Category: "FELHŐ / SZINKRONIZÁLÁS"},
	{Name: "rclone", ID: "", Category: "FELHŐ / SZINKRONIZÁLÁS"},
	{Name: "Cyberduck", ID: "", Category: "FELHŐ / SZINKRONIZÁLÁS"},
	{Name: "Mountain Duck", ID: "", Category: "FELHŐ / SZINKRONIZÁLÁS"},
	{Name: "Box Drive", ID: "", Category: "FELHŐ / SZINKRONIZÁLÁS"},
	{Name: "Koofr", ID: "", Category: "FELHŐ / SZINKRONIZÁLÁS"},
	{Name: "Seafile Client", ID: "", Category: "FELHŐ / SZINKRONIZÁLÁS"},
	{Name: "Bitwarden", ID: "", Category: "JELSZÓ / 2FA / BIZTONSÁG"},
	{Name: "1Password", ID: "", Category: "JELSZÓ / 2FA / BIZTONSÁG"},
	{Name: "KeePass", ID: "DominikReichl.KeePass", Category: "JELSZÓ / 2FA / BIZTONSÁG"},
	{Name: "KeePassXC", ID: "KeePassXCTeam.KeePassXC", Category: "JELSZÓ / 2FA / BIZTONSÁG"},
	{Name: "Proton Pass", ID: "", Category: "JELSZÓ / 2FA / BIZTONSÁG"},
	{Name: "Enpass", ID: "", Category: "JELSZÓ / 2FA / BIZTONSÁG"},
	{Name: "Authy", ID: "", Category: "JELSZÓ / 2FA / BIZTONSÁG"},
	{Name: "2FAS", ID: "", Category: "JELSZÓ / 2FA / BIZTONSÁG"},
	{Name: "Aegis (mobil)", ID: "", Category: "JELSZÓ / 2FA / BIZTONSÁG"},
	{Name: "Yubico Authenticator", ID: "", Category: "JELSZÓ / 2FA / BIZTONSÁG"},
	{Name: "Windows Defender", ID: "", Category: "JELSZÓ / 2FA / BIZTONSÁG"},
	{Name: "ESET", ID: "", Category: "JELSZÓ / 2FA / BIZTONSÁG"},
	{Name: "Sophos Home", ID: "", Category: "JELSZÓ / 2FA / BIZTONSÁG"},
	{Name: "GlassWire", ID: "", Category: "JELSZÓ / 2FA / BIZTONSÁG"},
	{Name: "SimpleWall", ID: "", Category: "JELSZÓ / 2FA / BIZTONSÁG"},
	{Name: "Portmaster", ID: "", Category: "JELSZÓ / 2FA / BIZTONSÁG"},
	{Name: "Slack", ID: "", Category: "EMAIL / KOMMUNIKÁCIÓ"},
	{Name: "Signal Desktop", ID: "", Category: "EMAIL / KOMMUNIKÁCIÓ"},
	{Name: "WhatsApp Desktop", ID: "", Category: "EMAIL / KOMMUNIKÁCIÓ"},
	{Name: "Viber", ID: "", Category: "EMAIL / KOMMUNIKÁCIÓ"},
	{Name: "Element", ID: "", Category: "EMAIL / KOMMUNIKÁCIÓ"},
	{Name: "Mattermost Desktop", ID: "", Category: "EMAIL / KOMMUNIKÁCIÓ"},
	{Name: "Rocket.Chat Desktop", ID: "", Category: "EMAIL / KOMMUNIKÁCIÓ"},
	{Name: "Thunderbird", ID: "", Category: "EMAIL / KOMMUNIKÁCIÓ"},
	{Name: "Mailspring", ID: "", Category: "EMAIL / KOMMUNIKÁCIÓ"},
	{Name: "eM Client", ID: "", Category: "EMAIL / KOMMUNIKÁCIÓ"},
	{Name: "Spark Desktop", ID: "", Category: "EMAIL / KOMMUNIKÁCIÓ"},
	{Name: "Proton Mail Bridge", ID: "", Category: "EMAIL / KOMMUNIKÁCIÓ"},
	{Name: "LibreWolf", ID: "", Category: "BÖNGÉSZŐK"},
	{Name: "Floorp", ID: "", Category: "BÖNGÉSZŐK"},
	{Name: "Waterfox", ID: "", Category: "BÖNGÉSZŐK"},
	{Name: "Tor Browser", ID: "", Category: "BÖNGÉSZŐK"},
	{Name: "Arc", ID: "", Category: "BÖNGÉSZŐK"},
	{Name: "Zen Browser", ID: "", Category: "BÖNGÉSZŐK"},
	{Name: "Chromium", ID: "", Category: "BÖNGÉSZŐK"},
	{Name: "Free Download Manager", ID: "", Category: "DOWNLOAD MANAGEREK"},
	{Name: "JDownloader 2", ID: "", Category: "DOWNLOAD MANAGEREK"},
	{Name: "Internet Download Manager", ID: "", Category: "DOWNLOAD MANAGEREK"},
	{Name: "Xtreme Download Manager", ID: "", Category: "DOWNLOAD MANAGEREK"},
	{Name: "Motrix", ID: "", Category: "DOWNLOAD MANAGEREK"},
	{Name: "aria2", ID: "", Category: "DOWNLOAD MANAGEREK"},
	{Name: "Persepolis Download Manager", ID: "", Category: "DOWNLOAD MANAGEREK"},
	{Name: "yt-dlp", ID: "", Category: "DOWNLOAD MANAGEREK"},
	{Name: "Gallery-dl", ID: "", Category: "DOWNLOAD MANAGEREK"},
	{Name: "Transmission", ID: "", Category: "TORRENT"},
	{Name: "Deluge", ID: "", Category: "TORRENT"},
	{Name: "BiglyBT", ID: "", Category: "TORRENT"},
	{Name: "Tixati", ID: "", Category: "TORRENT"},
	{Name: "Tribler", ID: "", Category: "TORRENT"},
}
